spring:
  datasource:
    url: jdbc:mysql://localhost:3307/sfg_prod
    username: sfg_prod_user
    password: eric
    platform: mysql
  jpa:
    hibernate:
      ddl-auto: validate
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    database: mysql
    show-sql: false